[agent]
  interval = "5s"
  flush_interval = "5s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["idc/proyecto/sergio/datos"]
  data_format = "json"
  json_name_key = ""
  tag_keys = ["estado", "indice_confort", "riesgo_moho"]

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "estacion_iot"
  username = "admin"
  password = "admin123"
